"""initial: create 9 core tables

Revision ID: 7daf452b3a1e
Revises:
Create Date: 2026-05-19 21:34:03.339215

"""
# ruff: noqa
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7daf452b3a1e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triggered_at', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('rule_name', sa.Text(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('warning','critical')", name='ck_alerts_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alpha_acceptance_daily',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('precision_at_20_pure', sa.Float(), nullable=True),
    sa.Column('precision_at_20_llm', sa.Float(), nullable=True),
    sa.Column('precision_at_10_pure', sa.Float(), nullable=True),
    sa.Column('precision_at_10_llm', sa.Float(), nullable=True),
    sa.Column('lift_at_20_pure', sa.Float(), nullable=True),
    sa.Column('lift_at_20_llm', sa.Float(), nullable=True),
    sa.Column('ic_pure', sa.Float(), nullable=True),
    sa.Column('ic_llm', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_lower_pure', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_upper_pure', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_lower_llm', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_upper_llm', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('metric_date'),
    comment='Alpha 验收口径每日记录；永久保留（小表）'
    )
    op.create_table('data_source_diff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('yfinance_value', sa.Float(), nullable=False),
    sa.Column('fallback_value', sa.Float(), nullable=False),
    sa.Column('fallback_source', sa.Text(), nullable=False),
    sa.Column('diff_pct', sa.Float(), nullable=False),
    sa.Column('alerted', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint("fallback_source IN ('stooq','alpaca','polygon')", name='ck_data_source_diff_fallback'),
    sa.CheckConstraint("field IN ('open','high','low','close','volume')", name='ck_data_source_diff_field'),
    sa.PrimaryKeyConstraint('id'),
    comment='备用 OHLCV 交叉校验差异；保留 365 天后归档至冷备份'
    )
    op.create_index('idx_data_source_diff_date', 'data_source_diff', ['metric_date'], unique=False)
    op.create_table('factor_health_daily',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('factor_name', sa.Text(), nullable=False),
    sa.Column('daily_ic', sa.Float(), nullable=True),
    sa.Column('rolling_ic_mean_90d', sa.Float(), nullable=True),
    sa.Column('cusum_value', sa.Float(), nullable=True),
    sa.Column('cusum_alert', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('consecutive_alerts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('metric_date', 'factor_name'),
    comment='CUSUM 快速监控时序；保留 365 天后归档至冷备份'
    )
    op.create_index('idx_factor_health_factor_date', 'factor_health_daily', ['factor_name', 'metric_date'], unique=False)
    op.create_table('factor_versions',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('released_at', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('parent_version', sa.Text(), nullable=True),
    sa.Column('release_type', sa.Text(), nullable=True),
    sa.CheckConstraint("release_type IN ('MAJOR','MINOR','PATCH')", name='ck_factor_versions_release_type'),
    sa.PrimaryKeyConstraint('version'),
    comment='因子版本配置；永久保留'
    )
    op.create_table('llm_cost_daily',
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('by_module_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cost_date')
    )
    op.create_table('monitoring_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('sampled_at', sa.Text(), nullable=False),
    sa.Column('rss_mb', sa.Float(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('open_fd_count', sa.Integer(), nullable=True),
    sa.Column('thread_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='资源监控采样；保留最近 30 天'
    )
    op.create_index('idx_monitoring_task_time', 'monitoring_samples', ['task_id', 'sampled_at'], unique=False)
    op.create_table('pid_lock',
    sa.Column('lock_name', sa.Text(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('acquired_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lock_name')
    )
    op.create_index('idx_pid_lock_expires', 'pid_lock', ['expires_at'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=False),
    sa.Column('breakout_probability', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('factor_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['factor_version'], ['factor_versions.version'], name='fk_paper_trades_factor_version'),
    sa.PrimaryKeyConstraint('id'),
    comment='Paper Trading / 实盘虚拟交易记录'
    )
    op.create_index('idx_paper_trades_signal_date', 'paper_trades', ['signal_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_paper_trades_signal_date', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('idx_pid_lock_expires', table_name='pid_lock')
    op.drop_table('pid_lock')
    op.drop_index('idx_monitoring_task_time', table_name='monitoring_samples')
    op.drop_table('monitoring_samples')
    op.drop_table('llm_cost_daily')
    op.drop_table('factor_versions')
    op.drop_index('idx_factor_health_factor_date', table_name='factor_health_daily')
    op.drop_table('factor_health_daily')
    op.drop_index('idx_data_source_diff_date', table_name='data_source_diff')
    op.drop_table('data_source_diff')
    op.drop_table('alpha_acceptance_daily')
    op.drop_table('alerts')
    # ### end Alembic commands ###
